src/Organization/HRExpert.Organization/ViewModels/Timesheet/Sicklist/SicklistListFilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.DataAnnotations;

namespace HRExpert.Organization.ViewModels
{
    using DTO;
    public class SicklistListFilterViewModel: FilterViewModelBase
    {
        [ContentFilter(ModelPropertyName ="Document.Person.Name", CheckAction = ContentFilterActions.StartsWith)]
        public string PersonName { get; set; }
        [ContentFilter(ModelPropertyName = "Document.Person.DepartmentId", CheckAction = ContentFilterActions.Equals)]
        public int? DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        [ContentFilter(ModelPropertyName = "Document.Event.BeginDate", CheckAction = ContentFilterActions.GreatOrEquals)]
        public DateTime? BeginDate { get; set; }
        [ContentFilter(ModelPropertyName = "Document.Event.EndDate", CheckAction = ContentFilterActions.LessOrEquals)]
        public DateTime? EndDate { get; set; }
        [ContentFilter(ModelPropertyName = "Document.DocumentStatusId", CheckAction = ContentFilterActions.Equals)]
        public int? DocumentStatusId { get; set; }
        [ContentFilter(ModelPropertyName = "StatusId", CheckAction = ContentFilterActions.Equals)]
        public int? ApproveStatusId { get; set; }
        [ContentFilter(ModelPropertyName = "Id", CheckAction = ContentFilterActions.Equals)]
        public int? DocumentId { get; set; }
        [ContentFilter(ModelPropertyName = "SicklistNumber", CheckAction = ContentFilterActions.Equals)]
        public int? SicklistNumber { get; set; }
    }
}

src/Organization/HRExpert.Organization/ViewModels/Timesheet/Sicklist/SicklistListViewModel.cs
namespace HRExpert.Organization.ViewModels
{
    public class SicklistListViewModel: DocumentsViewModelBase<DTO.DocumentDto<DTO.SicklistDto>,SicklistListFilterViewModel>
    {        
        public SicklistListViewModel()
        {
            this.Filter = new SicklistListFilterViewModel();
        }
    }
}

src/Organization/HRExpert.Organization/Controllers/Timesheet/Sicklist/SicklistBabyMindingTypesController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using HRExpert.Organization.DTO;
using HRExpert.Organization.BL.Abstractions;
namespace HRExpert.Organization.Controllers.Timesheet.Sicklist
{
    /// <summary>
    /// Типы больничных по уходу за ребенком
    /// </summary>
    public class SicklistBabyMindingTypesController: Controller
    {
        ISicklistBabyMindingTypesBL sicklistBabyMindingTypesBL;
        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="sicklistBabyMindingTypesBL"></param>
        public SicklistBabyMindingTypesController( ISicklistBabyMindingTypesBL sicklistBabyMindingTypesBL)
        {
            this.sicklistBabyMindingTypesBL = sicklistBabyMindingTypesBL;
        }
        /// <summary>
        /// Список записей
        /// </summary>
        /// <returns></returns>
        [HttpGet]        
        public List<SicklistBabyMindingTypeDto> List()
        {
            return this.sicklistBabyMindingTypesBL.List();
        }
    }
}

src/Organization/HRExpert.Organization/Controllers/Timesheet/Sicklist/SicklistController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using HRExpert.Organization.DTO;
using HRExpert.Organization.BL.Abstractions;
using ExtCore.Data.Abstractions;
namespace HRExpert.Organization.Controllers.Timesheet.Sicklist
{
    using ViewModels;
    /// <summary>
    /// Контроллер больничных
    /// </summary>
    public class SicklistController :Platformus.Barebone.Controllers.ControllerBase
    {
        ISicklistBL sicklistBL;
        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="sicklistBL"></param>
        public SicklistController(IStorage storage, ISicklistBL sicklistBL, IPersonEventBL personEventBL)
            :base(storage)
        {
            this.sicklistBL = sicklistBL;
        }
        #region API
        /*
        /// <summary>
        /// Список
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public List<DocumentDto<SicklistDto>> List()
        {
            return sicklistBL.List();
        }
        /// <summary>
        /// Чтение
        /// </summary>
        /// <param name="sicklistid"></param>
        /// <returns></returns>
        [HttpGet]
        public DocumentDto<SicklistDto> Read(int sicklistid)
        {
            return sicklistBL.Read(sicklistid);
        }
        /// <summary>
        /// Создание
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]        
        public DocumentDto<SicklistDto> Create([FromForm]DocumentDto<SicklistDto> value)
        {           
           return sicklistBL.Create(value);           
        }
        /// <summary>
        /// Редактирование
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPut]
        public DocumentDto<SicklistDto> Update([FromForm]DocumentDto<SicklistDto> value)
        {
            return sicklistBL.Update(value);
        }*/
        #endregion
        #region MVC
        [HttpGet]
        public IActionResult Index()
        {
            SicklistListViewModel model = new SicklistListViewModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult Index(SicklistListViewModel model)
        {
            model.Documents = this.sicklistBL.GetByFilterModel(model.Filter);
           
            return View(model);
        }
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var model = sicklistBL.Read(Id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(DocumentDto<SicklistDto> model)
        {
            Validate(model);
            if (ModelState.IsValid)
            {
                model = sicklistBL.Update(model);
            }
            else
            {
                model = sicklistBL.Read(model.Data.Id);
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var model = new DocumentDto<SicklistDto>();
            model.Approvements.Add(new DocumentApprovementDto() { ApprovePosition = 1 });
            model.Approvements.Add(new DocumentApprovementDto() { ApprovePosition = 2 });
            model.Approvements.Add(new DocumentApprovementDto() { ApprovePosition = 3 });
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(DocumentDto<SicklistDto> model)
        {
            Validate(model);
            if (ModelState.IsValid)
            {
                model = sicklistBL.Create(model);
                return RedirectToAction("Edit", "Sicklist", new { Id = model.Data.Id });
            }
            else return View(model);
        }

        public void Validate(DocumentDto<SicklistDto> model)
        {
            ModelState.Clear();
            if(model.Data.Id==0)
            {
                if (model.Data.SicklistDocument == null)
                    ModelState.AddModelError("Data.SicklistDocument", "Скан больничного листа обязателен");
            }
            if(!model.Data.BeginDate.HasValue)
            {
                ModelState.AddModelError("Data.BeginDate", "Дата начала обязательна");
            }
            if (!model.Data.EndDate.HasValue)
            {
                ModelState.AddModelError("Data.BeginDate", "Дата окончания обязательна");
            }
            if(model.Data.EndDate<model.Data.BeginDate)
            {
                ModelState.AddModelError("Data.BeginDate", "Дата начала должна быть меньше даты окончания");
            }
            if (string.IsNullOrEmpty(model.Data.SicklistNumber))
            {
                ModelState.AddModelError("Data.SicklistNumber", "Номер больничного обязателен");
            }
            if(model.Data.BeginDate.HasValue && model.Data.EndDate.HasValue)
            {                
                if(sicklistBL.CheckOtherDocuments(model))
                {
                    ModelState.AddModelError("Person.Id", "Для выбранного сотрудника существуют другие заявки в указаном интервале дат.");
                }
            }

        }
        [HttpGet]
        public IActionResult GetFile(int SicklistId, int fileType)
        {
            string filename;
            return File(sicklistBL.GetFile(SicklistId, fileType, out filename), "application/octet-stream", filename);
        }
        #endregion
    }
}

src/Organization/HRExpert.Organization/Controllers/Timesheet/Sicklist/SicklistPaymentPercentController.cs
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using HRExpert.Organization.DTO;
using HRExpert.Organization.BL.Abstractions;
namespace HRExpert.Organization.Controllers
{
    /// <summary>
    /// Контроллер процентов выплат
    /// </summary>
    /// 
    public class SicklistPaymentPercentController: Controller
    {
        ISicklistPaymentPercentBL sicklistPaymentPercentBL;
        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="sicklistPaymentPercentBL"></param>
        public SicklistPaymentPercentController(ISicklistPaymentPercentBL sicklistPaymentPercentBL)
        {
            this.sicklistPaymentPercentBL = sicklistPaymentPercentBL;
        }
        /// <summary>
        /// Список
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IEnumerable<SicklistPaymentPercentDto> List()
        {
            return this.sicklistPaymentPercentBL.List();
        }
    }
}

src/Organization/HRExpert.Organization/Controllers/Timesheet/Sicklist/SicklistPaymentRestrictTypesController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using HRExpert.Organization.DTO;
using HRExpert.Organization.BL.Abstractions;
namespace HRExpert.Organization.Controllers
{
    /// <summary>
    /// Ограничение выплат
    /// </summary>
    public class SicklistPaymentRestrictTypesController: Controller
    {
        ISicklistPaymentRestrictTypesBL sicklistPaymentRestrictTypesBL;
        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="sicklistPaymentRestrictTypesBL"></param>
        public SicklistPaymentRestrictTypesController(ISicklistPaymentRestrictTypesBL sicklistPaymentRestrictTypesBL)
        {
            this.sicklistPaymentRestrictTypesBL = sicklistPaymentRestrictTypesBL;
        }
        /// <summary>
        /// Список
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public List<SicklistPaymentRestrictTypeDto> List()
        {
            return this.sicklistPaymentRestrictTypesBL.List();
        }
    }
}

src/Organization/HRExpert.Organization/Controllers/Timesheet/Sicklist/SicklistTypesController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using HRExpert.Organization.DTO;
using HRExpert.Organization.BL.Abstractions;
namespace HRExpert.Organization.Controllers
{
    /// <summary>
    /// Типы больничных
    /// </summary>
    public class SicklistTypesController: Controller
    {
        private ISicklistTypeBL sicklistTypeBl;
        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="sicklistTypeBl"></param>
        public SicklistTypesController(ISicklistTypeBL sicklistTypeBl)
        {
            this.sicklistTypeBl = sicklistTypeBl;
        }
        /// <summary>
        /// Список
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public List<SicklistTypeDto> List()
        {
            return sicklistTypeBl.List();
        }
    }
}

src/Organization/HRExpert.Organization/ViewComponents/ReferencySelectViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExtCore.Data.Abstractions;
using Platformus.Barebone.ViewComponents;
using Microsoft.AspNetCore.Mvc;
namespace HRExpert.Organization.ViewComponents
{
    using ViewModels;
    using BL.Abstractions;
    public class ReferencySelectViewComponent : ViewComponent
    {
        private IReferenceBL referenceBL;
        public ReferencySelectViewComponent(IReferenceBL referenceBL)
        {
            this.referenceBL = referenceBL;
        }
        public async Task<IViewComponentResult> InvokeAsync(string referenceName , string fieldname, bool isEditable=true, int? currentValue = 0)
        {
            List<IdNameViewModel> options = referenceBL.List(referenceName).Select(x=>new IdNameViewModel { Id = x.Id, Name = x.Name }).ToList();
            ReferencySelectViewModel model = new ReferencySelectViewModel { FieldName = fieldname, SelectOptions = options };
            model.IsEditable = isEditable;
            if (currentValue.HasValue && currentValue.Value != 0)
            {
                model.CurrentValue = currentValue.Value;
            }
            return this.View(model);
        }
    }
}

src/Organization/HRExpert.Organization/Views/Sicklist/Create.cshtml
@using HRExpert.Organization.DTO
@using HRExpert.Organization.BL
@model DocumentDto<SicklistDto>
@{
    this.Layout = "_Layout";
    ViewBag.Title = "Создание заявки";
    object htmlAttributes = new { @class = "form-control" };    
    var Options = new { htmlAttributes = htmlAttributes };
}
<ul class="breadcrumb">
    <li><a href="#">Табель</a></li>
    <li>@Html.ActionLink("Больничные","Index","Sicklist")</li>
    <li>@ViewBag.Title</li>
</ul>
<form method="post" enctype="multipart/form-data">
    <div class="panel panel-default">
        <div class="panel-heading">Данные заявки</div>
            <div class="panel-body FormContainer">
                @Html.ValidationSummary()
                <fieldset class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-2" for="personName">Дата начала:</label>
                        <div class="col-sm-10">
                            @await Component.InvokeAsync("PersonSelect", new { fieldname = "Person.Id" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Дата начала:</label>
                        <div class="col-sm-10">
                            @Html.EditorFor(model => model.Data.BeginDate, Options)
                            @Html.ValidationMessageFor(model => model.Data.BeginDate)
                        </div>
                    </div>
                    <div class="form-group ">
                        <label class="col-sm-2">Дата окончания:</label>
                        <div class="col-sm-10">
                            @Html.EditorFor(model => model.Data.EndDate, Options)
                            @Html.ValidationMessageFor(model => model.Data.EndDate)
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="personName" class="col-sm-2">Назначить с:</label>
                        <div class="col-sm-10">
                            @Html.EditorFor(model => model.Data.PaymentBeginDate, Options)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Номер больничного листа:</label>
                        <div class="col-sm-10">
                            @Html.EditorFor(x => x.Data.SicklistNumber, Options)
                            @Html.ValidationMessageFor(model=>model.Data.SicklistNumber)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Тип больничного листа:</label>
                        <div class="col-sm-10">
                            @await Component.InvokeAsync("ReferencySelect", new { referenceName = ReferenceNames.SicklistTypes, fieldname = "Data.SicklistType.Id" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">В случае ухода за ребенком:</label>
                        <div class="col-sm-10">
                            @await Component.InvokeAsync("ReferencySelect", new { referenceName = ReferenceNames.SicklistBabyMindingTypes, fieldname = "Data.SicklistBabyMindingType.Id" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Процент оплаты заработка:</label>
                        <div class="col-sm-10">
                            @await Component.InvokeAsync("ReferencySelect", new { referenceName = ReferenceNames.SicklistPaymentPercent, fieldname = "Data.SicklistPaymentPercent.Id" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Ограничение заработка (пособия):</label>
                        <div class="col-sm-10">
                            @await Component.InvokeAsync("ReferencySelect", new { referenceName = ReferenceNames.SicklistPaymentRestrictTypes, fieldname = "Data.SicklistPaymentRestrictType.Id" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Снизить пособие за нарушение режима с:</label>
                        <div class="col-sm-10">
                            @Html.EditorFor(x => x.Data.PaymentDecreaseDate, Options)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Учитывать заработок предыдущих страхователей</label>
                        <div class="col-sm-10">
                            @Html.CheckBoxFor(x => x.Data.isPreviousPaymentCounted)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Доплачивать до среднего заработка</label>
                        <div class="col-sm-10">
                            @Html.CheckBoxFor(x => x.Data.isAddToFullPayment)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Больничный имеет продолжение</label>
                        <div class="col-sm-10">
                            @Html.EditorFor(x => x.Data.IsContinue)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Страховой стаж:</label>
                        <div class="col-sm-3">
                            @Html.EditorFor(x => x.Data.ExperienceYears, Options)
                        </div>
                        <label class="col-sm-1">лет</label>
                        <div class="col-sm-3">
                            @Html.EditorFor(x => x.Data.ExperienceMonth, Options)
                        </div>
                        <label class="col-sm-1">месяцев</label>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Заполнение табеля:</label>
                        <div class="col-sm-10">
                            @await Component.InvokeAsync("ReferencySelect", new { referenceName = ReferenceNames.TimesheetStatus, fieldname = "Data.TimesheetStatus.Id" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Скан документа:</label>
                        <div class="col-sm-10">
                            <input type="file" name="Data.SicklistDocument" />
                            @Html.ValidationMessageFor(model=>model.Data.SicklistDocument)
                        </div>
                    </div>
                </fieldset>
            </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body ControlsContainer">
            <input type="submit" class="btn btn-success" value="Создать" />
        </div>
    </div>
</form>
<script>    
    $(document).ready(function () {
        $('#Data_BeginDate').datepicker({ dateFormat: 'dd.mm.yy' });
        $('#Data_EndDate').datepicker({ dateFormat: 'dd.mm.yy' });
        $('#Data_PaymentDecreaseDate').datepicker({ dateFormat: 'dd.mm.yy' });
        $('#Data_PaymentBeginDate').datepicker({ dateFormat: 'dd.mm.yy' });

        $('[name="Data.SicklistType.Id"]').change(function () {
            var val = $(this).val();
            if (val == 4) {
                $('[name="Data.SicklistBabyMindingType.Id"]').prop("disabled", false);
            }
            else { $('[name="Data.SicklistBabyMindingType.Id"]').prop("disabled", true); }
        }
        );
        $('[name="Data.SicklistType.Id"]').change();
    });
</script>

src/Organization/HRExpert.Organization/Views/Sicklist/Index.cshtml
@using HRExpert.Organization.DTO
@using HRExpert.Organization.BL
@model HRExpert.Organization.ViewModels.SicklistListViewModel
@{
    this.Layout = "_Layout";
    ViewBag.Title = "Больничные";

}
<ul class="breadcrumb">
    <li><a href="#">Табель</a></li>
    <li><a href="#">@ViewBag.Title</a></li>
</ul>
<div class="panel panel-default">
    <div class="panel-heading">Фильтр</div>
    <div class="panel-body FilterContainer">
        <fieldset class="form-horizontal">
            <form method="post">
                @Html.HiddenFor(x => x.OrderBy)
                @Html.HiddenFor(x => x.OrderDirection)
                <div class="form-group ">
                    <label for="personName" class="col-sm-2">Подразделение:</label>
                    <div class="col-sm-10">
                        <div class="input-group">
                            <input type="text" class="form-control" id="Filter_DepartmentName" value="@Model.Filter.DepartmentName" name="Filter.DepartmentName"  readonly="readonly"/>
                            <div class="input-group-btn">
                                <input type="button" value="Выбрать" class="btn btn-default" id="Filter_DepartmentSelectButton" />
                            </div>
                        </div>
                        @Html.HiddenFor(x => x.Filter.DepartmentId)
                   </div>
                </div>
                <div class="form-group ">
                    <label for="personName" class="col-sm-2">ФИО сотрудника:</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Filter.PersonName, new { htmlAttributes = new { @class = "form-control", placeholder = "ФИО сотрудника" } })
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-sm-2">Номер заявки:</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Filter.DocumentId, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-sm-2">Номер больничного листа:</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Filter.SicklistNumber, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-sm-2">Статус документа:</label>
                    <div class="col-sm-10">
                        @await Component.InvokeAsync("ReferencySelect", new { referenceName = ReferenceNames.DocumentStatus, fieldname = "Filter.DocumentStatusId", isEditable = true, currentValue = Model.Filter.DocumentStatusId })
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-sm-2">Дата начала:</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Filter.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-sm-2">Дата окончания:</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Filter.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <button type="submit" class="btn btn-info">Выбрать</button>
                <input type="button" value="Очистить" class="btn btn-default" onclick="HRexpert.ClearFilter()" />
            </form>
        </fieldset>
    </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body ControlsContainer">
            <a href="@Url.Action("Create","Sicklist")" class="btn btn-primary">Создать заявку</a>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Заявки</div>
        <div class="panel-body TableContainer">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th onclick="ChangeSort('Data.Id')">Номер заявки</th>
                        <th onclick="ChangeSort('CreateDate')">Дата создания</th>
                        <th onclick="ChangeSort('Person.Name')">ФИО</th>
                        <th onclick="ChangeSort('Person.StaffEstablishedPost.Position.Name')">Должность</th>
                        <th onclick="ChangeSort('Person.StaffEstablishedPost.Department.Name')">Подразделение</th>
                        <th onclick="ChangeSort('Data.SicklistNumber')">Номер больничного листа</th>
                        <th onclick="ChangeSort('Data.SicklistType.Name')">Вид больничного</th>
                        <th onclick="ChangeSort('Data.BeginDate')">Дата начала</th>
                        <th onclick="ChangeSort('Data.EndDate')">Дата окончания</th>
                        <th onclick="ChangeSort('Data.Status.Name')">Статус документа</th>
                        <th onclick="ChangeSort('Data.ApproveStatus')">Этап согласования</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var element in Model.Documents)
            {
                        <tr>
                            <td>@Html.ActionLink(element.Data.Id.ToString(), "Edit", new { Id = element.Data.Id }) <span class="badge"></span></td>
                            <td>@element.CreateDate</td>
                            <td>@element.Person.Name</td>
                            <td>@element.Person.StaffEstablishedPost.Position.Name</td>
                            <td>@element.Person.StaffEstablishedPost.Department.Name</td>
                            <td>@element.Data.SicklistNumber</td>
                            <td>@element.Data.SicklistType.Name</td>
                            <td>@element.Data.BeginDate</td>
                            <td>@element.Data.EndDate</td>
                            <td>@element.Status?.Name</td>
                            <td>@element.Data.ApproveStatus</td>
                        </tr>
            }
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function ChangeSort(column) {
            var direction = $('#OrderDirection');
            var orderby = $('#OrderBy')
            if (orderby.val() == column) direction.val() = !direction.val();
            orderby.val(column);
            document.forms[0].submit();
        }
        $(document).ready(function () {
            HRexpert.TypicalInit();
            var DepartmentSelectDialog;
            $('#Filter_DepartmentSelectButton').click(function ()
            {
                HRexpert.Factory.CreateDepartmentSelectDialog('Filter_DepartmentId', 'Filter_DepartmentName',function(dialog){dialog.dialog('open');});
            });
        });
            
    </script>